### ISSUE TITLE
missing h1

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/template-design-system-de-l-etat#10]
Il manque une balise `h1` sur chaque page.
Ex :
- "Ce site est une démo" (page d'accueil)
- "Ceci est un très beau formulaire" (page formulaire)

**Comment by estellecomment** [comment]
Merci pour le signalement :)

**Comment by estellecomment** [comment]
@benoitdequick tu peux reviewer le fix ? https://github.com/betagouv/template-design-system-de-l-etat/pull/12
