### ISSUE TITLE
Non conformité de la taille du bloc-marque

### ISSUE THREAD

**Issue by djadela** [betagouv/template-design-system-de-l-etat#13]
Le logo ne semble pas être conforme à la charte : https://www.gouvernement.fr/charte/charte-graphique-les-applications/ministeres-secretariats-d-etat-services-deconcentres-ou-a-l   (sous-section « UI Kit »).  
Il devrait être plus gros pour que le "liberté, égalité, fraternité" soit lisible et la marianne à 20px de hauteur.

**Comment by jdauphant** [comment]
Bonjour,
La charte est indiqué pour le papier.
C'est le SIG qui a développé le design system, nous n'avons pas toucher le header. 

C'est même exactement la même taille de header que le site du SIG que vous avez pointé :
![image](https://user-images.githubusercontent.com/1238254/108045726-18238480-7044-11eb-98e9-30600681f690.png)
![image](https://user-images.githubusercontent.com/1238254/108045746-1ce83880-7044-11eb-9852-3e4ceb0d9303.png)
