### ISSUE TITLE
React DarkMode

### ISSUE THREAD

**Issue by yaniselmaleh** [betagouv/template-design-system-de-l-etat#20]
Bonjour, 

Dans l'attente du composant **DarkMode** officiel, voici un code maison pour le faire fonctionner sur du **React**, cependant il manque le style du switch 🙂

```js
import React, { useState, useEffect } from 'react'

export default function DarkMode() {
  const [schemeState, setschemeState] = useState(false);
  const SCHEME_ATTRIBUTE = 'data-rf-theme';

  useEffect(() => {
    const getscheme = localStorage.getItem('scheme');
    if (getscheme === 'dark') {
      setschemeState(true);
    }
  }, []);

  useEffect(() => {
    if (schemeState) {
      localStorage.setItem('scheme', 'dark');
      document.getElementsByTagName("html")[0].setAttribute(SCHEME_ATTRIBUTE, "dark");
    } else {
      localStorage.setItem('scheme', 'light');
      document.getElementsByTagName("html")[0].setAttribute(SCHEME_ATTRIBUTE, "light");
      return
    }
  }, [schemeState]);

  return (
    <>
      <button onClick={() => setschemeState(!schemeState)} id="DarkMode" className="rf-btn rf-btn--secondary" title="Changer le thème du site">
        {schemeState ? <>Mode Jour</> : <>Mode Nuit</>}
      </button>
    </>
  );
}
```

**Comment by astranchet** [comment]
Merci @yaniselmaleh ! Je prévois de rajouter à la page Ressources des liens vers des librairies (reacts ou autre). Est-ce que ce code est disponible sur un répo sinon ? Ou sur un gist ?

**Comment by yaniselmaleh** [comment]
Je vais créer le répo si besoins, avec uniquement ce bout de code ou sous une application react vierge ?

**Comment by astranchet** [comment]
@yaniselmaleh c'est toi le dev, moi je suis "juste" une designer (qui écrit du code HTML certes 😅) et qui rassemble les ressources utile au même endroit ! Fait ce qui te semble le plus pertinent pour être utile à d'autres, et le plus simple pour toi :)

**Comment by yaniselmaleh** [comment]
Bonjour @astranchet, voici le répo ;) 

https://github.com/yaniselmaleh/template-ds-react-darkmode

**Comment by yaniselmaleh** [comment]
Update, darkmode officiel : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/579928166/Param+tres+d+affichage+-+Switch+theme
