### ISSUE TITLE
Ajout de site ressource

### ISSUE THREAD

**Issue by yaniselmaleh** [betagouv/template-design-system-de-l-etat#32]
Bonjour @astranchet,

Serait-il possible d'ajouter le site https://www.civils.defense.gouv.fr/ & https://contractuels.civils.defense.gouv.fr/ sur votre page ressource 🙂

**Comment by astranchet** [comment]
Salut @yaniselmaleh , je note et je mène une petite enquête sur le Slack officiel du DSFR pour voir si d'autres sites pourraient être rajoutés par la même occasion
