### ISSUE TITLE
Hard to read the ticked checkbox when checkbox is disabled (for read only mode)

### ISSUE THREAD

**Issue by jeffmac-aix** [betagouv/template-design-system-de-l-etat#48]
Lorsque l'on désactive le composant checkbox alors que la case à cocher est cochée, il devient très difficile de visualiser qu'elle soit cochée (pas assez de contraste).

**Comment by estellecomment** [comment]
Merci de proposer des améliorations ! 

Pour que ta suggestion arrive à l'équipe qui développe le DS (c'est pas nous ! On a juste proposé un site de demo pour aider la communanuté), je regarde sur leur site (https://www.systeme-de-design.gouv.fr/) et je vois qu'ils ont un formulaire pour proposer des évolutions : https://gouvfr.atlassian.net/servicedesk/customer/portal/1/group/1/create/6

Donc je te suggère de passer par là. Merci pour ta participation active !

**Comment by jeffmac-aix** [comment]
Selon l'équipe du DSR, la dernière version va régler ce problème, le ticket étant de toutes les façons traité sur un autre système et par une autre équipe, je clos cette issue, merci encore pour la réponse rapide :)
