### ISSUE TITLE
APiLos utilise le système de design de l'état

### ISSUE THREAD

**Issue by kolok** [betagouv/template-design-system-de-l-etat#49]
La plateforme APiLos contribue à accélérer le versement de l’Aide Personnalisée au Logement (APL) et réduire l’insécurité locative dans le logement social.

Elle a pour mission de fiabiliser les déclarations de convention APL signées entre les bailleurs de logements sociaux et les services instructeurs de l'Etat.

Pour en savoir plus: https://beta.gouv.fr/startups/apilos.html

Plateforme disponible ici : https://apilos.beta.gouv.fr

**Comment by astranchet** [comment]
Merci de l'info, c'est en ligne (#51)
