### ISSUE TITLE
Site proudly built with the Dsfr 😉

### ISSUE THREAD

**Issue by jeremie-baboukhian** [betagouv/template-design-system-de-l-etat#50]
Salut 👋
Un petit nouveau 
https://france-identite.gouv.fr/

**Comment by astranchet** [comment]
Déjà en [ligne](https://template.incubateur.net/ressources) dès que je suis tombée dessus, car super exemple !
Si j'avais le temps, je m'inspirerais de la page d'accueil pour faire un template 😊

**Comment by jeremie-baboukhian** [comment]
Merci beaucoup j’avais même pas vu. 
🥰🥰

Envoyé depuis mon iPhone
